mydata=read.csv("C:/Users/musai/Desktop/DATA SCIENCE PRACTICALS/mydata.csv")
View(mydata)
library(dplyr)
a1=sample_n(mydata,10)
a2=sample_frac(mydata,.1)
a3=distinct(mydata,Index,.keep_all = FALSE)
a4=distinct(mydata,Index,.keep_all = TRUE)
a5=distinct(mydata,Index,Y2010,.keep_all = FALSE)
a6=select(mydata,-starts_with("y"))
a7=select(mydata,contains("I"))
a8=rename(mydata,mycol=Index)
library(ggplot2)
iris1=iris
plot(iris$Sepal.Length)
plot(iris$Sepal.Length,type = "l")
barplot(iris$Sepal.Length)
hist(iris$Sepal.Length)
table(iris$Species)
pie(table(iris$Species))
boxplot(iris$Sepal.Width)